services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
      args:
        EMBEDDING_MODEL_ID: ${EMBEDDING_MODEL_ID}
        EMBEDDING_SIZE: ${EMBEDDING_SIZE}
    volumes:
      - ${LOCAL_FILES_PATH}:/usr/src/app/local_files/
      - ./indexer_data:/indexer/storage
    ports:
      - 127.0.0.1:8001:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - CONTAINER_PATH=/usr/src/app/local_files/
      - RERANKER_MODEL=${RERANKER_MODEL}
      - RERANK_TOP_N=${RERANK_TOP_N}
      - RETRIEVAL_K=${RETRIEVAL_K}
      - CHUNK_SIZE=${CHUNK_SIZE:-650}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-300}
    depends_on:
      - qdrant